name = "PALSJulia"
uuid = "3ffa0026-5f68-41f0-beae-2f2b11b650a3"
version = "0.1.0"
authors = ["David Sagan <david.sagan@gmail.com>", "Alex He <adh236@cornell.edu>"]

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
